# Generated by Django 5.1.4 on 2026-05-06 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wdms_tenants', '0004_alter_region_created_date_alter_region_updated_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatorJurisdiction',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('NATIONAL', 'National'), ('REGIONAL', 'Regional')], default='NATIONAL', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, help_text='Required when scope is REGIONAL; null for NATIONAL regulators.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulator_jurisdictions', to='wdms_tenants.region')),
                ('regulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurisdictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regulator Jurisdiction',
                'verbose_name_plural': 'REGULATOR JURISDICTIONS',
                'db_table': 'regulator_jurisdictions',
                'unique_together': {('regulator', 'region')},
            },
        ),
    ]
