# Generated by Django 5.1.4 on 2026-04-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdms_documents', '0002_resize_embedding_768_and_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_warehou_b7faa0_idx',
            old_name='documents_warehou_1f1f00_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_documen_f2a694_idx',
            old_name='documents_documen_24c8bd_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_uploade_7be1c7_idx',
            old_name='documents_uploade_9b3c20_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtransition',
            new_name='workflow_tr_documen_a3d41a_idx',
            old_name='workflow_t_documen_3a7e4c_idx',
        ),
    ]
