# Generated by Django 5.1.4 on 2026-05-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdms_documents', '0003_rename_documents_warehou_1f1f00_idx_documents_warehou_b7faa0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uploadattempt',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uploadattempt',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
