# Generated by Django 5.1.4 on 2026-04-28 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VALIDATED', 'Document Validated'), ('DOCUMENT_CONFIRMED_BY_STAFF', 'Staff Confirmed Document'), ('DOCUMENT_APPROVED_BY_MANAGER', 'Manager Approved'), ('DOCUMENT_APPROVED_BY_CEO', 'CEO Approved'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('DOCUMENT_SENT_BACK', 'Document Sent Back for Correction'), ('DOCUMENT_APPROVED_FINAL', 'Document Officially Approved'), ('RANKING_REPORT_UPDATED', 'Ranking Report Updated')], max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('related_document_id', models.BigIntegerField(blank=True, null=True)),
                ('channels_sent', models.JSONField(blank=True, default=list)),
                ('read_on_dashboard', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'NOTIFICATION EVENTS',
                'db_table': 'notification_events',
                'ordering': ['-primary_key'],
                'indexes': [models.Index(fields=['recipient', 'read_on_dashboard'], name='notificatio_recipie_c389db_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VALIDATED', 'Document Validated'), ('DOCUMENT_CONFIRMED_BY_STAFF', 'Staff Confirmed Document'), ('DOCUMENT_APPROVED_BY_MANAGER', 'Manager Approved'), ('DOCUMENT_APPROVED_BY_CEO', 'CEO Approved'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('DOCUMENT_SENT_BACK', 'Document Sent Back for Correction'), ('DOCUMENT_APPROVED_FINAL', 'Document Officially Approved'), ('RANKING_REPORT_UPDATED', 'Ranking Report Updated')], max_length=50)),
                ('channel', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('EMAIL', 'Email'), ('SMS', 'Short Message Service')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'NOTIFICATION PREFERENCES',
                'db_table': 'notification_preferences',
                'unique_together': {('user', 'event_type', 'channel')},
            },
        ),
    ]
