# Generated by Django 5.1.4 on 2026-05-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdms_tenants', '0003_alter_region_created_by_alter_tenant_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
