# Generated by Django 5.1.4 on 2026-05-06 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wdms_tenants', '0004_alter_region_created_date_alter_region_updated_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseRanking',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('computation_date', models.DateField(auto_now_add=True)),
                ('score_components', models.JSONField(default=dict, help_text='Intermediate score components used to derive the final score.')),
                ('final_score', models.FloatField(default=0.0, help_text='0–100 composite score; higher is better.')),
                ('risk_category', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='MEDIUM', max_length=8)),
                ('ai_explanation', models.TextField(blank=True, default='', help_text='Human-readable explanation of the score generated by the LLM.')),
                ('contributing_factors', models.JSONField(default=list, help_text='Ordered list of the biggest positive/negative contributors.')),
                ('is_latest', models.BooleanField(db_index=True, default=True, help_text='Only one row per warehouse should be True at a time.')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='wdms_tenants.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Ranking',
                'verbose_name_plural': 'WAREHOUSE RANKINGS',
                'db_table': 'warehouse_rankings',
                'ordering': ['-computation_date'],
                'indexes': [models.Index(fields=['warehouse', 'is_latest'], name='warehouse_r_warehou_34d010_idx')],
            },
        ),
    ]
