"""
Reporting models.

WarehouseRanking stores pre-computed ranking scores.  The nightly Celery Beat
job (and the on-demand recompute endpoint) writes rows here.  Only the latest
row per warehouse has is_latest=True so the current ranking is trivially
queryable without an expensive subquery.
"""

from __future__ import annotations

from django.db import models

from wdms_tenants.models import Warehouse
from wdms_utils.BaseModel import BaseModel


class RiskCategory(models.TextChoices):
    LOW = "LOW", "Low Risk"
    MEDIUM = "MEDIUM", "Medium Risk"
    HIGH = "HIGH", "High Risk"


class WarehouseRanking(BaseModel):
    """
    Rule-based compliance ranking for a warehouse, optionally enriched with an
    AI-generated explanation.

    Score components are stored as JSON so the scoring formula can evolve
    without schema changes.  Example shape::

        {
            "approved_ratio": 0.82,
            "correction_ratio": 0.05,
            "inspection_coverage": 0.6,
            "recent_activity_days": 14
        }
    """

    warehouse = models.ForeignKey(
        Warehouse,
        related_name="rankings",
        on_delete=models.CASCADE,
    )
    computation_date = models.DateField(auto_now_add=True)
    score_components = models.JSONField(
        default=dict,
        help_text="Intermediate score components used to derive the final score.",
    )
    final_score = models.FloatField(
        default=0.0,
        help_text="0–100 composite score; higher is better.",
    )
    risk_category = models.CharField(
        max_length=8,
        choices=RiskCategory.choices,
        default=RiskCategory.MEDIUM,
    )
    ai_explanation = models.TextField(
        blank=True,
        default="",
        help_text="Human-readable explanation of the score generated by the LLM.",
    )
    contributing_factors = models.JSONField(
        default=list,
        help_text="Ordered list of the biggest positive/negative contributors.",
    )
    is_latest = models.BooleanField(
        default=True,
        db_index=True,
        help_text="Only one row per warehouse should be True at a time.",
    )

    class Meta:
        db_table = "warehouse_rankings"
        verbose_name = "Warehouse Ranking"
        verbose_name_plural = "WAREHOUSE RANKINGS"
        ordering = ["-computation_date"]
        indexes = [
            models.Index(fields=["warehouse", "is_latest"]),
        ]

    def __str__(self) -> str:
        return f"{self.warehouse.name} — score {self.final_score:.1f} ({self.risk_category})"
